version: "3.9"

services:
  neo4j:
    image: neo4j:5.26.18
    container_name: neo4j_primekg
    restart: always
    ports:
      - "7474:7474"
      - "7687:7687"
    environment:
      - NEO4J_AUTH=neo4j/12345678
      - NEO4J_PLUGINS=["apoc", "graph-data-science"]
      - NEO4J_apoc_import_file_enabled=true
      - NEO4J_apoc_export_file_enabled=true
      - NEO4J_dbms_security_procedures_unrestricted=apoc.*,gds.*
      - NEO4J_dbms_security_allow__csv__import__from__file__urls=true
      - NEO4J_server_directories_import=/import
      - NEO4J_server_memory_heap_initial__size=3G
      - NEO4J_server_memory_heap_max__size=3G
      - NEO4J_server_memory_pagecache_size=4G

    volumes:
      - neo4j_data:/data
      - ./logs:/logs
      - ./data/primekg/import:/import

    healthcheck:
      test: ["CMD-SHELL", "wget --no-verbose --tries=1 --spider localhost:7474 || exit 1"]
      interval: 10s
      timeout: 10s
      retries: 10

volumes:
  neo4j_data:
    name: medcot_primekg_data
    external: true